feat/carto
betagouv/pass-sport pull request #197
Opened 2024-06-20 14:20 UTC by maxime-chaillet

2024-06-26 08:19 UTC, Destinyyyy requested changes
La cartographie en version pro ne fonctionne pas

2024-06-26 08:19 UTC, Destinyyyy commented on site/src/app/v2/trouver-un-club/components/club-filters/geolocation-filter/GeolocationFilter.tsx
> +    }, 300);
Je suggère de mettre 700.
300 c'est trop court, l'event matomo se trigger inutilement lorsqu'on bouge le slider un peu trop lentement
```suggestion
    }, 700);
```

2024-06-26 08:19 UTC, Destinyyyy commented on site/src/app/v2/trouver-un-club/components/club-list-view/ClubListView.tsx
> +    <div>
Pas besoin d'un div, un fragment suffit
```suggestion
    <>
```

2024-06-26 08:19 UTC, Destinyyyy commented on site/src/app/v2/trouver-un-club/components/club-filters/geolocation-filter/GeolocationFilter.tsx
> +  const isVisible: boolean = !(loading || !!error);
Pas besoin de spécifier le type, il est inféré
```suggestion
  const isVisible = !(loading || !!error);
```

2024-06-26 08:19 UTC, Destinyyyy commented on site/src/app/v2/trouver-un-club/components/club-filters/geolocation-filter/GeolocationFilter.tsx
> +};
Pas besoin de fragment
```suggestion
  return (
    isVisible && (
      <Range
        hintText="Dans un rayon autour de"
        label="Autour de moi"
        max={200}
        min={10}
        suffix=" km"
        step={10}
        nativeInputProps={{
          defaultValue: defaultDistance,
          onChange: (e: React.FormEvent<HTMLInputElement>) => {
            setSelectedDistance(e.currentTarget.value);
          },
        }}
        className={cn('fr-py-2w', styles.width)}
      />
    )
  );
```

2024-06-26 08:19 UTC, Destinyyyy commented on site/src/app/v2/trouver-un-club/components/club-finder/ClubFinder.tsx
> +  };
Typo sur searchQ**U**eryParam et simplification suggérée
```suggestion
  const getParameterFromQuery = (searchQueryParam: keyof typeof SEARCH_QUERY_PARAMS) => {
    const param = searchParams && searchParams.get(SEARCH_QUERY_PARAMS[searchQueryParam]);

    if (searchQueryParam === 'isShowingMapTab') {
      return parseInt(param) === 1 ? param : undefined;
    }

    return undefined;
  };
```

2024-06-26 08:19 UTC, Destinyyyy commented on site/src/app/v2/trouver-un-club/page.tsx
> +      <Suspense fallback={<p>Loading</p>}>
```suggestion
      <Suspense fallback={<p>En cours de chargement</p>}>
```

2024-06-26 09:48 UTC, maxime-chaillet commented on site/src/app/v2/trouver-un-club/components/club-filters/geolocation-filter/GeolocationFilter.tsx
> +    }, 300);
J'avais mis 300 pour garder de la fluidité en évitant d'attendre trop longtemps avant la pris en compte du chgmt de distance. Je mets 700 et on verra à l'usage.

2024-06-26 09:53 UTC, maxime-chaillet commented on site/src/app/v2/trouver-un-club/components/club-filters/geolocation-filter/GeolocationFilter.tsx
> +};
le fragment était là car on ne peut pas mettre une expression {...} juste derrière un return. J'ai simplifié qd même.

2024-06-26 09:58 UTC, maxime-chaillet commented on site/src/app/v2/trouver-un-club/components/club-finder/ClubFinder.tsx
> +  };
ca prend pas le cas ou param = 0 à priori.

2024-06-26 11:22 UTC, Destinyyyy requested changes
Il faut encodeURIComponent le nom des clubs sur la map

https://github.com/betagouv/pass-sport/assets/1215376/de33eee4-68ef-40f7-9842-a753ee83fcfc

2024-06-26 13:00 UTC, Destinyyyy approved these changes

2024-07-11 08:59 UTC, Destinyyyy commented on site/src/app/v2/trouver-un-club/components/club-filters/geolocation-filter/GeolocationFilter.tsx
> +      hintText={`${error ? 'Vous devez authoriser la geolocalisation pour utiliser ce filtre' : ''}. Dans un rayon autour de `}
Petit typo
<img width="523" alt="Screenshot 2024-07-11 at 10 59 41" src="https://github.com/betagouv/pass-sport/assets/1215376/eb45ef36-128d-44bb-ab2d-ca196f604573">

2024-07-11 09:08 UTC, Destinyyyy commented on site/src/app/v2/trouver-un-club/components/club-filters/geolocation-filter/GeolocationFilter.tsx
> +      hintText={`${error ? 'Vous devez authoriser la geolocalisation pour utiliser ce filtre' : ''}. Dans un rayon autour de `}
Également, le label "Autour de moi" ne trigger pas le check box

2024-07-11 13:50 UTC, Destinyyyy approved these changes

2024-07-15 07:51 UTC, merged