setup next app
betagouv/pass-sport pull request #2
Opened 2024-02-21 15:48 UTC by maxime-chaillet

2024-02-22 10:05 UTC, P3rceval commented on site/src/app/globals.css
> +  --font-mono: ui-monospace, Menlo, Monaco, "Cascadia Mono", "Segoe UI Mono",
@maxime-chaillet Peut-être qu'on peut supprimer les modules / styles / images par défaut ?

2024-02-22 13:26 UTC, maxime-chaillet commented on site/src/app/globals.css
> +  --font-mono: ui-monospace, Menlo, Monaco, "Cascadia Mono", "Segoe UI Mono",
oui, tout a fait. (j'avais pas fini)

2024-02-22 13:56 UTC, P3rceval commented on site/src/app/globals.css
> +  --font-mono: ui-monospace, Menlo, Monaco, "Cascadia Mono", "Segoe UI Mono",
Comme sur gitlab, tu peux mettre tes PR en draft et les passer en ready une fois que c'est bon :)

2024-02-23 09:42 UTC, P3rceval requested changes

2024-02-23 09:42 UTC, P3rceval commented on site/package.json
> +    "format:check": "prettier --check --ignore-path .gitignore \"**/*.+(ts|tsx|json|mjs)\"",
Peut-être qu'on devrait utiliser eslint plutot que prettier pour le formattage ? Normalement Eslint doit pouvoir embarquer prettier

2024-02-26 09:44 UTC, maxime-chaillet commented on site/.nvmrc
> +20
J'ai choisi la 20 car elle est LTS

2024-02-26 10:01 UTC, maxime-chaillet commented on site/package.json
> +    "format:check": "prettier --check --ignore-path .gitignore \"**/*.+(ts|tsx|json|mjs)\"",
Comme discuté, on garde prettier et on verra plus tard si necessaire

2024-02-26 10:17 UTC, P3rceval approved these changes

2024-02-26 10:17 UTC, merged