show basic info only
betagouv/pass-sport pull request #23
Opened 2024-04-08 06:35 UTC by maxime-chaillet

2024-04-08 11:10 UTC, P3rceval commented on site/src/app/v2/trouver-un-club/[club-name]/page.tsx
> +  const club = {
Pourquoi ne pas avoir utilisé l'API ?

2024-04-08 11:11 UTC, P3rceval requested changes

2024-04-08 11:11 UTC, P3rceval commented on site/src/app/v2/trouver-un-club/[club-name]/page.tsx
> +      <div className={styles['medical-certificate']}>
Composant react à part pour ce bandeau ?

2024-04-08 11:11 UTC, P3rceval commented on site/src/app/v2/trouver-un-club/[club-name]/page.tsx
> +            <Button priority="tertiary" size="large">
Périnne a mis l'URL sur les maquettes je crois. Si c'est pas le cas, n'hésites pas à lui demander :)

2024-04-11 20:00 UTC, maxime-chaillet commented on site/src/app/v2/trouver-un-club/[club-name]/page.tsx
> +      <div className={styles['medical-certificate']}>
fixé

2024-04-11 20:01 UTC, maxime-chaillet commented on site/src/app/v2/trouver-un-club/[club-name]/page.tsx
> +  const club = {
fixé

2024-04-11 20:01 UTC, maxime-chaillet commented on site/src/app/v2/trouver-un-club/[club-name]/page.tsx
> +            <Button priority="tertiary" size="large">
fixé

2024-04-15 09:37 UTC, maxime-chaillet commented on site/src/app/v2/trouver-un-club/[club-name]/page.tsx
> +  if (!club) {
bof. Il faudrait alors faire un truc comme ca return (<>{ club && <>....</>}</>). Ca fait de l'indentation en plus et ca me semble moins lisible.

2024-04-15 09:47 UTC, maxime-chaillet commented on site/src/app/components/pass-sport-breadcrumb/PassSportBreadcrumb.tsx
> +  const clubName = decodeURI(pathNames[pathNames.length - 1]);
`useRouter` en mode 'app router' ne permet pas de faire ca à ma connaissance. ( en mode `pages router` oui). Je préfère laissé tel quel si c'est ok pour toi. La doc de useRouter [ici](https://nextjs.org/docs/app/api-reference/functions/use-router#userouter)

2024-04-15 12:14 UTC, P3rceval commented on site/src/app/components/pass-sport-breadcrumb/PassSportBreadcrumb.tsx
> +  const clubName = decodeURI(pathNames[pathNames.length - 1]);
Ca marche en mode page aussi. C'est ok pour moi de laisser comme ça mais j''pense qu'il faudra peut-être basculer sur `useRouter` à termes pour avoir un maximum de composants en SSR

2024-04-15 12:15 UTC, P3rceval approved these changes

2024-04-15 12:17 UTC, merged