Feat/add siret input for pro contact form
betagouv/pass-sport pull request #279
Opened 2024-09-02 12:36 UTC by maxime-chaillet

2024-09-02 14:43 UTC, P3rceval requested changes

2024-09-02 14:43 UTC, P3rceval commented on site/src/app/v2/une-question/components/ContactForm/ContactForm.tsx
> +    console.log('coucou');
```suggestion
```

2024-09-02 14:43 UTC, P3rceval commented on site/src/app/v2/une-question/components/ContactForm/ContactForm.tsx
> +    console.log('isvalid', isValid);
```suggestion
```

2024-09-03 09:36 UTC, P3rceval approved these changes

2024-09-03 14:51 UTC, Destinyyyy approved these changes

2024-09-04 13:58 UTC, merged